In [ ]:
import pandas as pd

In [ ]:
import pandas as pd

# Load data from a CSV file
data_file = "HDI.csv"  # Replace with your CSV file path
df = pd.read_csv(data_file)

df.head()

,ISO3,Country,Human Development Groups,UNDP Developing Regions,HDI Rank (2021),Human Development Index (1990),Human Development Index (1991),Human Development Index (1992),Human Development Index (1993),Human Development Index (1994),...,Material footprint per capita (tonnes) (2012),Material footprint per capita (tonnes) (2013),Material footprint per capita (tonnes) (2014),Material footprint per capita (tonnes) (2015),Material footprint per capita (tonnes) (2016),Material footprint per capita (tonnes) (2017),Material footprint per capita (tonnes) (2018),Material footprint per capita (tonnes) (2019),Material footprint per capita (tonnes) (2020),Material footprint per capita (tonnes) (2021)
0,AFG,Afghanistan,Low,SA,180.0,0.273,0.279,0.287,0.297,0.292,...,1.86,1.88,1.66,1.62,1.66,1.41,1.32,1.38,1.38,1.38
1,AGO,Angola,Medium,SSA,148.0,NaN,NaN,NaN,NaN,NaN,...,4.09,4.53,3.97,3.59,2.79,2.64,2.28,2.18,2.18,2.18
2,ALB,Albania,High,ECA,67.0,0.647,0.629,0.614,0.617,0.624,...,12.44,11.49,13.14,12.61,14.39,14.46,12.85,12.96,12.96,12.96
3,AND,Andorra,Very High,NaN,40.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ARE,United Arab Emirates,Very High,AS,26.0,0.728,0.739,0.742,0.748,0.755,...,49.56,49.68,55.49,59.76,64.95,75.61,65.97,68.95,68.95,68.95

In [ ]:
import pandas as pd

# List of columns to keep (including "Mean Years of Schooling" from 1990 to 2021)
columns_to_keep = [
    'Country',
    'Human Development Index (1990)', 'Human Development Index (1991)', 'Human Development Index (1992)',
    'Human Development Index (1993)', 'Human Development Index (1994)', 'Human Development Index (1995)',
    'Human Development Index (1996)', 'Human Development Index (1997)', 'Human Development Index (1998)',
    'Human Development Index (1999)', 'Human Development Index (2000)', 'Human Development Index (2001)',
    'Human Development Index (2002)', 'Human Development Index (2003)', 'Human Development Index (2004)',
    'Human Development Index (2005)', 'Human Development Index (2006)', 'Human Development Index (2007)',
    'Human Development Index (2008)', 'Human Development Index (2009)', 'Human Development Index (2010)',
    'Human Development Index (2011)', 'Human Development Index (2012)', 'Human Development Index (2013)',
    'Human Development Index (2014)', 'Human Development Index (2015)', 'Human Development Index (2016)',
    'Human Development Index (2017)', 'Human Development Index (2018)', 'Human Development Index (2019)',
    'Human Development Index (2020)', 'Human Development Index (2021)',
    'Expected Years df = of Schooling (1990)', 'Expected Years of Schooling (1991)',
    'Expected Years of Schooling (1992)', 'Expected Years of Schooling (1993)',
    'Expected Years of Schooling (1994)', 'Expected Years of Schooling (1995)',
    'Expected Years of Schooling (1996)', 'Expected Years of Schooling (1997)',
    'Expected Years of Schooling (1998)', 'Expected Years of Schooling (1999)',
    'Expected Years of Schooling (2000)', 'Expected Years of Schooling (2001)',
    'Expected Years of Schooling (2002)', 'Expected Years of Schooling (2003)',
    'Expected Years of Schooling (2004)', 'Expected Years of Schooling (2005)',
    'Expected Years of Schooling (2006)', 'Expected Years of Schooling (2007)',
    'Expected Years of Schooling (2008)', 'Expected Years of Schooling (2009)',
    'Expected Years of Schooling (2010)', 'Expected Years of Schooling (2011)',
    'Expected Years of Schooling (2012)', 'Expected Years of Schooling (2013)',
    'Expected Years of Schooling (2014)', 'Expected Years of Schooling (2015)',
    'Expected Years of Schooling (2016)', 'Expected Years of Schooling (2017)',
    'Expected Years of Schooling (2018)', 'Expected Years of Schooling (2019)',
    'Expected Years of Schooling (2020)', 'Expected Years of Schooling (2021)',
    'Mean Years of Schooling (1990)', 'Mean Years of Schooling (1991)', 'Mean Years of Schooling (1992)',
    'Mean Years of Schooling (1993)', 'Mean Years of Schooling (1994)', 'Mean Years of Schooling (1995)',
    'Mean Years of Schooling (1996)', 'Mean Years of Schooling (1997)', 'Mean Years of Schooling (1998)',
    'Mean Years of Schooling (1999)', 'Mean Years of Schooling (2000)', 'Mean Years of Schooling (2001)',
    'Mean Years of Schooling (2002)', 'Mean Years of Schooling (2003)', 'Mean Years of Schooling (2004)',
    'Mean Years of Schooling (2005)', 'Mean Years of Schooling (2006)', 'Mean Years of Schooling (2007)',
    'Mean Years of Schooling (2008)', 'Mean Years of Schooling (2009)', 'Mean Years of Schooling (2010)',
    'Mean Years of Schooling (2011)', 'Mean Years of Schooling (2012)', 'Mean Years of Schooling (2013)',
    'Mean Years of Schooling (2014)', 'Mean Years of Schooling (2015)', 'Mean Years of Schooling (2016)',
    'Mean Years of Schooling (2017)', 'Mean Years of Schooling (2018)', 'Mean Years of Schooling (2019)',
    'Mean Years of Schooling (2020)', 'Mean Years of Schooling (2021)'
]

# Keep only the columns in the list
df_filtered = df[columns_to_keep]

In [ ]:
output_file = "processed_literacy_rates.csv"
df_filtered.to_csv(output_file, index=False)
print(f"DataFrame has been saved to {output_file}")

DataFrame has been saved to processed_literacy_rates.csv

In [ ]:
import pandas as pd

In [ ]:
file_gdp = "GDP.csv"
df_gdp = pd.read_csv(file_gdp)
print("GDP DataFrame columns:", df_gdp.columns)
if 'code' in df_gdp.columns:
    df_gdp = df_gdp.drop(columns=['code'])
df_gdp.rename(columns={"entity": "Country"}, inplace=True)
df_gdp.replace("..", pd.NA, inplace=True)
df_gdp.head()

GDP DataFrame columns: Index(['entity', 'code', 'GDP per Capita 1990', 'GDP per Capita 1991',
       'GDP per Capita 1992', 'GDP per Capita 1993', 'GDP per Capita 1994',
       'GDP per Capita 1995', 'GDP per Capita 1996', 'GDP per Capita 1997',
       'GDP per Capita 1998', 'GDP per Capita 1999', 'GDP per Capita 2000',
       'GDP per Capita 2001', 'GDP per Capita 2002', 'GDP per Capita 2003',
       'GDP per Capita 2004', 'GDP per Capita 2005', 'GDP per Capita 2006',
       'GDP per Capita 2007', 'GDP per Capita 2008', 'GDP per Capita 2009',
       'GDP per Capita 2010', 'GDP per Capita 2011', 'GDP per Capita 2012',
       'GDP per Capita 2013', 'GDP per Capita 2014', 'GDP per Capita 2015',
       'GDP per Capita 2016', 'GDP per Capita 2017', 'GDP per Capita 2018',
       'GDP per Capita 2019', 'GDP per Capita 2020', 'GDP per Capita 2021',
       'GDP per Capita 2022', 'GDP per Capita 2023'],
      dtype='object')

,Country,GDP per Capita 1990,GDP per Capita 1991,GDP per Capita 1992,GDP per Capita 1993,GDP per Capita 1994,GDP per Capita 1995,GDP per Capita 1996,GDP per Capita 1997,GDP per Capita 1998,...,GDP per Capita 2014,GDP per Capita 2015,GDP per Capita 2016,GDP per Capita 2017,GDP per Capita 2018,GDP per Capita 2019,GDP per Capita 2020,GDP per Capita 2021,GDP per Capita 2022,GDP per Capita 2023
0,Afghanistan,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,575.146245808546,565.569730408751,563.872336723147,562.769574140988,553.125151688293,557.861533207459,527.834554499306,408.625855217403,377.665627080705,379.707497269884
1,Albania,1606.29646776458,1163.49159838489,1086.4387714304,1197.58090750054,1305.00106057165,1488.02088119627,1633.55200001885,1464.29796254199,1603.64765027651,...,3855.76074409659,3952.80357364813,4090.37272829183,4249.8200493985,4431.55559506989,4542.26866282892,4417.04105105395,4858.05201500931,5154.8274975368,5419.63779125273
2,Algeria,3605.68701213527,3478.5097627463,3455.9293629926,3302.91950571082,3201.56914405705,3255.187268716,3322.9553813945,3297.46603365919,3410.88254399624,...,4634.10149183949,4685.05902729002,4768.73140080218,4742.90075536604,4717.00358853556,4672.66408682198,4363.68533766912,4456.74687641147,4544.46688059647,4660.40545686886
3,American Samoa,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,12203.0894714284,12727.4102651386,12665.2829921268,11930.7771236826,12412.6024074562,12524.0160252283,13194.274740128,13233.5784817341,13709.0974895473,<NA>
4,Andorra,31143.1468745802,29642.305980666,28161.9424927346,26518.2336327363,26587.1383037195,27619.5060608184,28871.2160741757,31140.6896808445,31800.3640667052,...,37300.6244183478,38654.9347203095,40085.0205971586,39361.0622634329,39242.1448960772,39346.2750344286,34536.6499209948,36929.0191515162,39780.3966116268,40227.2335282714

In [ ]:
file_gini = "Gini.csv"
df_gini=pd.read_csv(file_gini)
df_gini = df_gini.drop(columns=["Code"])
df_gini.rename(columns={"Entity": "Country"}, inplace=True)
df_gini

,Country,Gini coefficient 1990,Gini coefficient 1991,Gini coefficient 1992,Gini coefficient 1993,Gini coefficient 1994,Gini coefficient 1995,Gini coefficient 1996,Gini coefficient 1997,Gini coefficient 1998,...,Gini coefficient 2014,Gini coefficient 2015,Gini coefficient 2016,Gini coefficient 2017,Gini coefficient 2018,Gini coefficient 2019,Gini coefficient 2020,Gini coefficient 2021,Gini coefficient 2022,Gini coefficient 2023
0,Albania,0.270103,0.270103,0.270103,0.270103,0.270103,0.270103,0.270103,0.270103,0.270103,...,0.345989,0.327537,0.337363,0.330557,0.301483,0.301158,0.294196,0.294196,0.294196,0.294196
1,Algeria,0.353301,0.353301,0.353301,0.353301,0.353301,0.353301,0.353301,0.353301,0.353301,...,0.276157,0.276157,0.276157,0.276157,0.276157,0.276157,0.276157,0.276157,0.276157,0.276157
2,Angola,0.519447,0.519447,0.519447,0.519447,0.519447,0.519447,0.519447,0.519447,0.519447,...,0.427155,0.427155,0.427155,0.427155,0.512640,0.512640,0.512640,0.512640,0.512640,0.512640
3,Argentina (urban),0.467545,0.467545,0.454552,0.448434,0.458985,0.488787,0.494914,0.490859,0.507132,...,0.418225,0.418225,0.423450,0.414348,0.417190,0.433142,0.427438,0.424456,0.407365,0.407365
4,Armenia,0.362197,0.362197,0.362197,0.362197,0.362197,0.362197,0.362197,0.362197,0.362197,...,0.314833,0.323568,0.325479,0.336218,0.344335,0.300312,0.251316,0.279401,0.279453,0.279453
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,Venezuela,0.420618,0.420618,0.420618,0.420618,0.420618,0.471673,0.471673,0.471673,0.479997,...,0.446993,0.446993,0.446993,0.446993,0.446993,0.446993,0.446993,0.446993,0.446993,0.446993
176,Vietnam,0.356540,0.356540,0.356540,0.356540,0.356540,0.356540,0.356540,0.354422,0.354422,...,0.347554,0.347554,0.352667,0.352667,0.357155,0.357155,0.367902,0.367902,0.360930,0.360930
177,Yemen,0.349978,0.349978,0.349978,0.349978,0.349978,0.349978,0.349978,0.349978,0.349978,...,0.367071,0.367071,0.367071,0.367071,0.367071,0.367071,0.367071,0.367071,0.367071,0.367071
178,Zambia,0.594029,0.594029,0.594029,0.525501,0.525501,0.525501,0.483284,0.483284,0.491221,...,0.520111,0.558376,0.558376,0.558376,0.558376,0.558376,0.558376,0.558376,0.514831,0.514831
179,Zimbabwe,0.431536,0.431536,0.431536,0.431536,0.431536,0.431536,0.431536,0.431536,0.431536,...,0.431536,0.431536,0.431536,0.443371,0.443371,0.502564,0.502564,0.502564,0.502564,0.502564

In [ ]:
file_hdi = "HDI.csv"
df_hdi = pd.read_csv(file_hdi)
df_hdi.replace("NaN", pd.NA, inplace=True)
df_hdi.head()

,Country,Human Development Index (1990),Human Development Index (1991),Human Development Index (1992),Human Development Index (1993),Human Development Index (1994),Human Development Index (1995),Human Development Index (1996),Human Development Index (1997),Human Development Index (1998),...,Mean Years of Schooling (2012),Mean Years of Schooling (2013),Mean Years of Schooling (2014),Mean Years of Schooling (2015),Mean Years of Schooling (2016),Mean Years of Schooling (2017),Mean Years of Schooling (2018),Mean Years of Schooling (2019),Mean Years of Schooling (2020),Mean Years of Schooling (2021)
0,Afghanistan,0.273,0.279,0.287,0.297,0.292,0.310,0.319,0.323,0.324,...,2.209473,2.261614,2.313755,2.365896,2.463660,2.561425,2.659189,2.756953,2.854718,2.985070
1,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.909642,3.950166,3.990690,4.704040,5.417391,5.417391,5.417391,5.417391,5.417391,5.417391
2,Albania,0.647,0.629,0.614,0.617,0.624,0.634,0.645,0.642,0.657,...,10.025110,10.196281,10.370374,10.547439,10.727528,10.910692,11.096983,11.286455,11.286455,11.286455
3,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.587085,10.616062,10.645040,10.573280,10.556100,10.555773,10.555446,10.555120,10.555120,10.555120
4,United Arab Emirates,0.728,0.739,0.742,0.748,0.755,0.762,0.767,0.773,0.779,...,10.169965,10.338129,10.506293,10.674456,10.842620,12.055400,12.484000,12.694030,12.694030,12.694030

In [ ]:
file_infra = "Infrastructure.csv"
df_infra = pd.read_csv(file_infra)
df_infra.head()

,Country,Average Power Line,Average Schools,Average Supermarkets,Average Public Roads,Average Hospitals
0,Ukraine,2.0,0.4,1.2,31.4,1.0
1,UAE,1.8,5.4,4.8,44.8,0.6
2,Argentina,2.0,10.0,9.0,8.6,3.6
3,Austria,3.4,15.6,10.2,45.0,1.0
4,Australia,8.0,16.0,10.8,69.8,1.8

In [ ]:
file_net = "Internet.csv"
df_net = pd.read_csv(file_net)
df_net = df_net.drop(columns=["code"])
df_net.rename(columns={"entity": "Country"}, inplace=True)
df_net.head()

,Country,Internet Usage (% of Population) 1990,Internet Usage (% of Population) 1991,Internet Usage (% of Population) 1992,Internet Usage (% of Population) 1993,Internet Usage (% of Population) 1994,Internet Usage (% of Population) 1995,Internet Usage (% of Population) 1996,Internet Usage (% of Population) 1997,Internet Usage (% of Population) 1998,...,Internet Usage (% of Population) 2014,Internet Usage (% of Population) 2015,Internet Usage (% of Population) 2016,Internet Usage (% of Population) 2017,Internet Usage (% of Population) 2018,Internet Usage (% of Population) 2019,Internet Usage (% of Population) 2020,Internet Usage (% of Population) 2021,Internet Usage (% of Population) 2022,Internet Usage (% of Population) 2023
0,Afghanistan,0,0,0,0,0,0,..,..,..,...,7,8.26,11,13.5,16.8,17.6,18.4,..,..,..
1,Albania,0,0,0,0,0,0.011168695,0.032196828,0.048593919,0.06502737,...,54.3,56.9,59.6,62.4,65.4,68.5504,72.2377,79.3237,82.6137,83.1356
2,Algeria,0,0,0,0,0.000360674,0.001768954,0.001738533,0.010268463,0.020238555,...,29.5,38.2,42.9455,47.6911,49.0385,58.9776,60.6534,66.2356,71.2432,..
3,American Samoa,0,0,0,0,0,0,..,..,..,...,..,..,..,..,..,..,..,..,..,..
4,Andorra,0,0,0,0,0,0,1.526601023,3.050175385,6.886209218,...,86.1,87.9,89.7,91.5675,..,90.7187,93.2056,93.8975,94.4855,..

In [ ]:
file_lit = "Literacy.csv"
df_lit = pd.read_csv(file_lit)
df_lit = df_lit.drop(columns=["Code"])
df_lit.rename(columns={"Entity": "Country"}, inplace=True)
df_lit

,Country,Literacy rate 1990,Literacy rate 1991,Literacy rate 1992,Literacy rate 1993,Literacy rate 1994,Literacy rate 1995,Literacy rate 1996,Literacy rate 1997,Literacy rate 1998,...,Literacy rate 2014,Literacy rate 2015,Literacy rate 2016,Literacy rate 2017,Literacy rate 2018,Literacy rate 2019,Literacy rate 2020,Literacy rate 2021,Literacy rate 2022,Literacy rate 2023
0,Afghanistan,31.00000,31.00000,31.00000,31.00000,31.00000,31.00000,31.00000,31.00000,31.00000,...,31.00000,33.75384,33.75384,33.75384,33.75384,33.75384,33.75384,37.00000,37.00000,37.00000
1,Albania,99.00000,99.00000,99.00000,99.00000,99.00000,99.00000,99.00000,99.00000,99.00000,...,97.00000,97.55390,97.55390,98.81623,98.81623,98.81623,98.81623,98.81623,98.50000,98.50000
2,Algeria,70.00000,70.00000,70.00000,70.00000,70.00000,70.00000,70.00000,70.00000,70.00000,...,75.00000,79.60840,79.60840,79.60840,81.40784,81.40784,81.40784,81.40784,81.40784,81.40784
3,Andorra,100.00000,100.00000,100.00000,100.00000,100.00000,100.00000,100.00000,100.00000,100.00000,...,100.00000,100.00000,100.00000,100.00000,100.00000,100.00000,100.00000,100.00000,100.00000,100.00000
4,Angola,67.00000,67.00000,67.00000,67.00000,67.00000,67.00000,67.00000,67.00000,67.00000,...,66.00000,66.23586,66.23586,66.23586,66.23586,66.23586,66.23586,66.23586,72.40000,72.40000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,Western and Central Africa (WB),43.57052,44.36271,45.13663,45.95827,46.83009,47.00222,47.86489,48.86634,50.23897,...,54.14114,55.00662,55.46578,56.47220,59.74735,59.55367,59.70324,60.00732,60.29085,60.50555
256,World,74.90692,75.28641,75.69422,76.10236,76.50139,76.91177,77.29624,79.28838,80.46865,...,85.28639,85.67888,86.00011,86.17700,86.43748,86.54791,86.74745,86.92751,87.15533,87.35600
257,Yemen,37.00000,37.00000,37.00000,37.00000,37.00000,37.00000,37.00000,37.00000,37.00000,...,68.78942,69.96195,69.96195,69.96195,69.96195,69.96195,69.96195,69.96195,69.96195,69.96195
258,Zambia,65.00000,65.00000,65.00000,65.00000,65.00000,65.00000,65.00000,65.00000,65.00000,...,83.00000,85.11726,85.11726,85.11726,71.13230,71.13230,87.50000,87.50000,87.50000,87.50000
259,Zimbabwe,84.00000,84.00000,84.00000,84.00000,84.00000,84.00000,84.00000,84.00000,84.00000,...,88.69342,86.87348,86.87348,86.87348,86.87348,93.22755,93.22755,93.22755,89.85000,89.85000

In [ ]:
# Merge multiple DataFrames step by step
combined_df = pd.merge(df_gini, df_gdp, how="outer", on="Country")
combined_df = pd.merge(combined_df, df_hdi, how="outer", on="Country")
combined_df = pd.merge(combined_df, df_infra, how="outer", on="Country")
combined_df = pd.merge(combined_df, df_lit, how="outer", on="Country")
combined_df = pd.merge(combined_df, df_net, how="outer", on="Country")

# Display the resulting DataFrame
print(combined_df)

                         Country  Gini coefficient 1990  \
0                    Afghanistan                    NaN
1    Africa Eastern and Southern                    NaN
2     Africa Western and Central                    NaN
3                        Albania               0.270103
4                        Algeria               0.353301
..                           ...                    ...
355                          NaN                    NaN
356                          NaN                    NaN
357                          NaN                    NaN
358                          NaN                    NaN
359                          NaN                    NaN

     Gini coefficient 1991  Gini coefficient 1992  Gini coefficient 1993  \
0                      NaN                    NaN                    NaN
1                      NaN                    NaN                    NaN
2                      NaN                    NaN                    NaN
3                 0.270103               0.270103               0.270103
4                 0.353301               0.353301               0.353301
..                     ...                    ...                    ...
355                    NaN                    NaN                    NaN
356                    NaN                    NaN                    NaN
357                    NaN                    NaN                    NaN
358                    NaN                    NaN                    NaN
359                    NaN                    NaN                    NaN

     Gini coefficient 1994  Gini coefficient 1995  Gini coefficient 1996  \
0                      NaN                    NaN                    NaN
1                      NaN                    NaN                    NaN
2                      NaN                    NaN                    NaN
3                 0.270103               0.270103               0.270103
4                 0.353301               0.353301               0.353301
..                     ...                    ...                    ...
355                    NaN                    NaN                    NaN
356                    NaN                    NaN                    NaN
357                    NaN                    NaN                    NaN
358                    NaN                    NaN                    NaN
359                    NaN                    NaN                    NaN

     Gini coefficient 1997  Gini coefficient 1998  ...  \
0                      NaN                    NaN  ...
1                      NaN                    NaN  ...
2                      NaN                    NaN  ...
3                 0.270103               0.270103  ...
4                 0.353301               0.353301  ...
..                     ...                    ...  ...
355                    NaN                    NaN  ...
356                    NaN                    NaN  ...
357                    NaN                    NaN  ...
358                    NaN                    NaN  ...
359                    NaN                    NaN  ...

     Internet Usage (% of Population) 2014  \
0                                        7
1                                     12.1
2                                     14.9
3                                     54.3
4                                     29.5
..                                     ...
355                                    NaN
356                                    NaN
357                                    NaN
358                                    NaN
359                                    NaN

     Internet Usage (% of Population) 2015  \
0                                     8.26
1                                     14.3
2                                     17.2
3                                     56.9
4                                     38.2
..                                     ...
355                                    NaN
356                                    NaN
357                                    NaN
358                                    NaN
359                                    NaN

     Internet Usage (% of Population) 2016  \
0                                       11
1                                     15.7
2                                     19.9
3                                     59.6
4                                  42.9455
..                                     ...
355                                    NaN
356                                    NaN
357                                    NaN
358                                    NaN
359                                    NaN

     Internet Usage (% of Population) 2017  \
0                                     13.5
1                                     17.4
2                                     23.2
3                                     62.4
4                                  47.6911
..                                     ...
355                                    NaN
356                                    NaN
357                                    NaN
358                                    NaN
359                                    NaN

     Internet Usage (% of Population) 2018  \
0                                     16.8
1                                     19.8
2                                     25.7
3                                     65.4
4                                  49.0385
..                                     ...
355                                    NaN
356                                    NaN
357                                    NaN
358                                    NaN
359                                    NaN

     Internet Usage (% of Population) 2019  \
0                                     17.6
1                                     22.8
2                                     28.9
3                                  68.5504
4                                  58.9776
..                                     ...
355                                    NaN
356                                    NaN
357                                    NaN
358                                    NaN
359                                    NaN

     Internet Usage (% of Population) 2020  \
0                                     18.4
1                                       26
2                                     32.4
3                                  72.2377
4                                  60.6534
..                                     ...
355                                    NaN
356                                    NaN
357                                    NaN
358                                    NaN
359                                    NaN

     Internet Usage (% of Population) 2021  \
0                                       ..
1                                     29.5
2                                     34.3
3                                  79.3237
4                                  66.2356
..                                     ...
355                                    NaN
356                                    NaN
357                                    NaN
358                                    NaN
359                                    NaN

     Internet Usage (% of Population) 2022  \
0                                       ..
1                                     31.4
2                                     36.9
3                                  82.6137
4                                  71.2432
..                                     ...
355                                    NaN
356                                    NaN
357                                    NaN
358                                    NaN
359                                    NaN

     Internet Usage (% of Population) 2023
0                                       ..
1                                     34.9
2                                     39.4
3                                  83.1356
4                                       ..
..                                     ...
355                                    NaN
356                                    NaN
357                                    NaN
358                                    NaN
359                                    NaN

[360 rows x 238 columns]

In [ ]:
df_gini.rename(columns={"entity": "Entity"}, inplace=True)
df_gdp.rename(columns={"entity": "Entity"}, inplace=True)
df_gdp.rename(columns={"code": "Code"}, inplace=True)
df_gini.rename(columns={"code": "Code"}, inplace=True)
df_gini.replace("..", pd.NA, inplace=True)
df_gdp.replace("..", pd.NA, inplace=True)
df_gdp.head()

,Entity,Code,GDP per Capita 1990,GDP per Capita 1991,GDP per Capita 1992,GDP per Capita 1993,GDP per Capita 1994,GDP per Capita 1995,GDP per Capita 1996,GDP per Capita 1997,...,GDP per Capita 2014,GDP per Capita 2015,GDP per Capita 2016,GDP per Capita 2017,GDP per Capita 2018,GDP per Capita 2019,GDP per Capita 2020,GDP per Capita 2021,GDP per Capita 2022,GDP per Capita 2023
0,Afghanistan,AFG,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,575.146245808546,565.569730408751,563.872336723147,562.769574140988,553.125151688293,557.861533207459,527.834554499306,408.625855217403,377.665627080705,379.707497269884
1,Albania,ALB,1606.29646776458,1163.49159838489,1086.4387714304,1197.58090750054,1305.00106057165,1488.02088119627,1633.55200001885,1464.29796254199,...,3855.76074409659,3952.80357364813,4090.37272829183,4249.8200493985,4431.55559506989,4542.26866282892,4417.04105105395,4858.05201500931,5154.8274975368,5419.63779125273
2,Algeria,DZA,3605.68701213527,3478.5097627463,3455.9293629926,3302.91950571082,3201.56914405705,3255.187268716,3322.9553813945,3297.46603365919,...,4634.10149183949,4685.05902729002,4768.73140080218,4742.90075536604,4717.00358853556,4672.66408682198,4363.68533766912,4456.74687641147,4544.46688059647,4660.40545686886
3,American Samoa,ASM,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,12203.0894714284,12727.4102651386,12665.2829921268,11930.7771236826,12412.6024074562,12524.0160252283,13194.274740128,13233.5784817341,13709.0974895473,<NA>
4,Andorra,AND,31143.1468745802,29642.305980666,28161.9424927346,26518.2336327363,26587.1383037195,27619.5060608184,28871.2160741757,31140.6896808445,...,37300.6244183478,38654.9347203095,40085.0205971586,39361.0622634329,39242.1448960772,39346.2750344286,34536.6499209948,36929.0191515162,39780.3966116268,40227.2335282714

In [ ]:
combined_df = pd.merge(df_gini, df_gdp, how="inner", on=["Entity", "Code"])

# Display the combined dataset
print(combined_df)

# Save to a new CSV file
combined_df.to_csv("combined_dataset.csv", index=False)

         Entity Code  Gini coefficient 1990  Gini coefficient 1991  \
0       Albania  ALB               0.270103               0.270103
1       Algeria  DZA               0.353301               0.353301
2        Angola  AGO               0.519447               0.519447
3       Armenia  ARM               0.362197               0.362197
4     Australia  AUS               0.325786               0.325786
..          ...  ...                    ...                    ...
142     Uruguay  URY               0.459414               0.459414
143  Uzbekistan  UZB               0.442685               0.442685
144     Vanuatu  VUT               0.373513               0.373513
145      Zambia  ZMB               0.594029               0.594029
146    Zimbabwe  ZWE               0.431536               0.431536

     Gini coefficient 1992  Gini coefficient 1993  Gini coefficient 1994  \
0                 0.270103               0.270103               0.270103
1                 0.353301               0.353301               0.353301
2                 0.519447               0.519447               0.519447
3                 0.362197               0.362197               0.362197
4                 0.325786               0.325786               0.325786
..                     ...                    ...                    ...
142               0.459414               0.459414               0.459414
143               0.442685               0.442685               0.442685
144               0.373513               0.373513               0.373513
145               0.594029               0.525501               0.525501
146               0.431536               0.431536               0.431536

     Gini coefficient 1995  Gini coefficient 1996  Gini coefficient 1997  ...  \
0                 0.270103               0.270103               0.270103  ...
1                 0.353301               0.353301               0.353301  ...
2                 0.519447               0.519447               0.519447  ...
3                 0.362197               0.362197               0.362197  ...
4                 0.325786               0.325786               0.325786  ...
..                     ...                    ...                    ...  ...
142               0.459414               0.459414               0.459414  ...
143               0.442685               0.442685               0.442685  ...
144               0.373513               0.373513               0.373513  ...
145               0.525501               0.483284               0.483284  ...
146               0.431536               0.431536               0.431536  ...

     GDP per Capita 2014  GDP per Capita 2015  GDP per Capita 2016  \
0       3855.76074409659     3952.80357364813     4090.37272829183
1       4634.10149183949     4685.05902729002     4768.73140080218
2       3300.73510980871     3213.90261080059     3020.98332805417
3       3393.09252326884     3512.39350276709     3533.88503607007
4       56327.8533063277     56739.0265346593     57401.0662268939
..                   ...                  ...                  ...
142     17122.0364563225     17125.9016800298     17357.2349882717
143     2659.99075095143     2803.19018021751     2918.67725852871
144     2798.19313971776     2746.59171880997     2812.11360434484
145     1299.01241762504     1295.87788680068     1303.57513869133
146     1377.25456014874     1386.42284717709     1379.62834257428

     GDP per Capita 2017  GDP per Capita 2018  GDP per Capita 2019  \
0        4249.8200493985     4431.55559506989     4542.26866282892
1       4742.90075536604     4717.00358853556     4672.66408682198
2       2911.60084214038     2775.74642272991     2664.43850995544
3        3815.3747426037     4027.83393010979     4343.45839583019
4       57750.6482221688     58530.7821697117      58924.733646242
..                   ...                  ...                  ...
142     17611.6036681064     17608.9441264801     17758.4384253485
143     2995.76761437609     3108.16187861097     3259.36964632427
144     2920.84492140374     2934.41548444085     2959.73897696398
145     1308.76829240086     1321.25045711573     1301.18132976178
146     1415.35133209501     1464.31529361767     1350.30985088104

     GDP per Capita 2020  GDP per Capita 2021  GDP per Capita 2022  \
0       4417.04105105395     4858.05201500931      5154.8274975368
1       4363.68533766912     4456.74687641147     4544.46688059647
2       2433.37637275564     2385.44881834294     2382.02263952585
3       4032.09043454955     4264.79961505187     4791.00481712183
4        58132.798523626      59276.503107197     61009.8077147403
..                   ...                  ...                  ...
142     16439.3140406635     17365.2637779599     18213.6956137768
143     3249.05191093933     3442.72484450189        3576.71552716
144     2747.30576044379     2642.67305152596      2631.5518630347
145     1228.73500113195     1269.10821808895      1298.8480495593
146     1224.27231433409     1305.22011277711     1361.91453034818

     GDP per Capita 2023
0       5419.63779125273
1       4660.40545686886
2       2332.88691268977
3       5151.01273118105
4       61583.9188935304
..                   ...
142     18295.9066764742
143     3725.67414578523
144     2627.97526807247
145     1330.85998216751
146      1410.7373112787

[147 rows x 70 columns]